// Generated by VUEO CloudStream Converter KissKH adapter.
// Source behaviour: Luckez12/Cloudstream-Repo KissKH.kt.

var KISSKH_VERSION = "2.8.10";
var KISSKH_MAIN = "https://kisskh.id";
var KISSKH_VIDEO_KEY_API = "https://script.google.com/macros/s/AKfycbzn8B31PuDxzaMa9_CQ0VGEDasFqfzI5bXvjaIZH4DM8DNq9q6xj1ALvZNz_JT3jF0suA/exec?id=";
var KISSKH_SUBTITLE_KEY_API = "https://script.google.com/macros/s/AKfycbyq6hTj0ZhlinYC6xbggtgo166tp6XaDKBCGtnYk8uOfYBUFwwxBui0sGXiu_zIFmA/exec?id=";
var KISSKH_UA = "Mozilla/5.0 (Linux; Android 15) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0 Mobile Safari/537.36";

function kkNow() { return Date.now ? Date.now() : 0; }

function kkLog(stage, status, detail, startedAt) {
  var ms = startedAt ? kkNow() - startedAt : 0;
  console.log(
    "[KissKH][converter] stage=" + stage +
    " status=" + status +
    (ms ? " ms=" + ms : "") +
    (detail ? " " + detail : "")
  );
}

function kkError(stage, detail) {
  return new Error("[KissKH][converter] stage=" + stage + " " + String(detail || "failed"));
}

function kkFetch(url, options, timeoutMs, asText) {
  return new Promise(function(resolve, reject) {
    var done = false;
    var timer = setTimeout(function() {
      if (!done) {
        done = true;
        reject(new Error("timeout"));
      }
    }, timeoutMs || 9000);

    fetch(url, options || {}).then(function(response) {
      if (!response || !response.ok) {
        throw new Error("HTTP " + (response ? response.status : "unknown"));
      }
      return asText ? response.text() : response.json();
    }).then(function(value) {
      if (!done) {
        done = true;
        clearTimeout(timer);
        resolve(value);
      }
    }, function(error) {
      if (!done) {
        done = true;
        clearTimeout(timer);
        reject(error);
      }
    });
  });
}

function kkHeaders(extra) {
  var out = {
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-US,en;q=0.9",
    "User-Agent": KISSKH_UA,
    "Referer": KISSKH_MAIN + "/"
  };
  Object.keys(extra || {}).forEach(function(key) { out[key] = extra[key]; });
  return out;
}

function kkDecode(value) {
  return String(value || "")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&#x27;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");
}

function kkMeta(html, key) {
  var escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  var p1 = new RegExp('<meta[^>]+(?:property|name)=["\\\']' + escaped + '["\\\'][^>]+content=["\\\']([^"\\\']+)["\\\']', 'i');
  var p2 = new RegExp('<meta[^>]+content=["\\\']([^"\\\']+)["\\\'][^>]+(?:property|name)=["\\\']' + escaped + '["\\\']', 'i');
  var m = html.match(p1) || html.match(p2);
  return m && m[1] ? kkDecode(m[1]).trim() : "";
}

function kkResolveTmdb(tmdbId, mediaType) {
  var started = kkNow();
  var type = String(mediaType || "").toLowerCase() === "tv" ? "tv" : "movie";
  var url = "https://www.themoviedb.org/" + type + "/" + encodeURIComponent(String(tmdbId)) + "?language=en-US";

  return kkFetch(url, {
    method: "GET",
    headers: {
      "Accept": "text/html,*/*",
      "Accept-Language": "en-US,en;q=0.9",
      "User-Agent": KISSKH_UA
    }
  }, 11000, true).then(function(html) {
    var raw = kkMeta(html, "og:title") || kkMeta(html, "twitter:title");
    if (!raw) {
      var tag = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
      raw = tag && tag[1] ? tag[1] : "";
    }
    var title = kkDecode(raw).replace(/\s+/g, " ").replace(/\s*[|\-\u2013\u2014]\s*(?:The Movie Database.*|TMDB.*)$/i, "").trim();
    var year = null;
    var ym = title.match(/\((19|20)\d{2}\)\s*$/);
    if (ym) {
      year = parseInt(ym[0].replace(/[()]/g, ""), 10);
      title = title.replace(/\s*\((19|20)\d{2}\)\s*$/, "").trim();
    }
    if (!title) throw kkError("tmdb", "title missing");
    kkLog("tmdb", "ok", "title=" + JSON.stringify(title) + " year=" + String(year || "?"), started);
    return { title: title, year: year, mediaType: type };
  });
}

function kkNormalize(value) {
  return String(value || "").toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, " ").replace(/\s+/g, " ").trim();
}

function kkTitleScore(actual, wanted) {
  actual = kkNormalize(actual);
  wanted = kkNormalize(wanted);
  if (!actual || !wanted) return 0;
  if (actual === wanted) return 140;
  if (actual.replace(/\s/g, "") === wanted.replace(/\s/g, "")) return 128;
  if (actual.indexOf(wanted) >= 0 || wanted.indexOf(actual) >= 0) return 78;
  var a = actual.split(" ").filter(Boolean);
  var b = wanted.split(" ").filter(Boolean);
  var overlap = a.filter(function(word) { return b.indexOf(word) >= 0; }).length;
  return Math.round((overlap / Math.max(a.length, b.length, 1)) * 55);
}

function kkSearch(metadata) {
  var started = kkNow();
  var url = KISSKH_MAIN + "/api/DramaList/Search?q=" + encodeURIComponent(metadata.title) + "&type=0";
  return kkFetch(url, { method: "GET", headers: kkHeaders() }, 8500, false).then(function(items) {
    if (!Array.isArray(items)) throw kkError("search", "unexpected response");
    var ranked = items.filter(function(item) { return item && item.id && item.title; }).map(function(item) {
      return { item: item, score: kkTitleScore(item.title, metadata.title) };
    }).sort(function(a, b) { return b.score - a.score; }).slice(0, 5);
    if (!ranked.length || ranked[0].score < 65) throw kkError("search", "no candidate for " + JSON.stringify(metadata.title));
    kkLog("search", "ok", "candidate=" + JSON.stringify(ranked[0].item.title) + " score=" + ranked[0].score, started);
    return { metadata: metadata, ranked: ranked };
  });
}

function kkLoadDetails(searchResult) {
  var metadata = searchResult.metadata;
  var ranked = searchResult.ranked;

  function next(index, best) {
    if (index >= ranked.length) {
      if (best) return Promise.resolve(best);
      return Promise.reject(kkError("detail", "no usable details"));
    }
    var item = ranked[index].item;
    var url = KISSKH_MAIN + "/api/DramaList/Drama/" + encodeURIComponent(String(item.id)) + "?isq=false";
    return kkFetch(url, { method: "GET", headers: kkHeaders() }, 8500, false).then(function(detail) {
      var score = ranked[index].score;
      var year = detail && detail.releaseDate ? parseInt(String(detail.releaseDate).slice(0, 4), 10) : null;
      var dtype = String(detail && detail.type || "").toLowerCase();
      if (metadata.year && year === metadata.year) score += 28;
      if (metadata.mediaType === "movie" && dtype === "movie") score += 28;
      if (metadata.mediaType === "tv" && dtype !== "movie") score += 20;
      var candidate = { metadata: metadata, detail: detail, score: score };
      var better = !best || candidate.score > best.score ? candidate : best;
      if (candidate.score >= 155) return candidate;
      return next(index + 1, better);
    }).catch(function() { return next(index + 1, best); });
  }

  return next(0, null).then(function(selected) {
    kkLog("detail", "ok", "id=" + String(selected.detail.id || "") + " score=" + selected.score);
    return selected;
  });
}

function kkSelectEpisode(result, season, episode) {
  var detail = result.detail || {};
  var episodes = Array.isArray(detail.episodes) ? detail.episodes.slice() : [];
  if (!episodes.length) throw kkError("episode", "no episodes");
  var target = parseFloat(String(episode || "1"));
  var selected = null;
  for (var i = 0; i < episodes.length; i += 1) {
    var number = parseFloat(String(episodes[i].number));
    if (!isNaN(number) && number === target) { selected = episodes[i]; break; }
  }
  if (!selected && (String(detail.type || "").toLowerCase() === "movie" || episodes.length === 1)) selected = episodes[0];
  if (!selected || !selected.id) throw kkError("episode", "episode " + String(episode || 1) + " not found");
  kkLog("episode", "ok", "episodeId=" + selected.id + " number=" + String(selected.number) + " season=" + String(season || 1));
  return { metadata: result.metadata, detail: detail, episode: selected };
}

function kkKey(base, episodeId, stage) {
  return kkFetch(base + encodeURIComponent(String(episodeId)) + "&version=" + encodeURIComponent(KISSKH_VERSION), {
    method: "GET",
    headers: { "Accept": "application/json,*/*", "User-Agent": KISSKH_UA }
  }, 8500, false).then(function(json) {
    var key = json && json.key ? String(json.key) : "";
    if (!key) throw kkError(stage, "empty key");
    return key;
  });
}

function kkSlug(value) {
  return String(value || "").replace(/[^a-zA-Z0-9]/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
}

function kkEpisodeNumber(value) {
  var n = Number(value);
  if (isNaN(n)) return "";
  return n % 1 === 0 ? String(parseInt(n, 10)) : String(n);
}

function kkQuality(url) {
  var m = String(url || "").match(/(2160|1440|1080|720|576|540|480|360)/i);
  return m ? m[1] + "p" : "Auto";
}

function kkType(url) {
  var lower = String(url || "").toLowerCase();
  if (lower.indexOf(".m3u8") >= 0) return "m3u8";
  if (lower.indexOf(".mpd") >= 0) return "dash";
  if (lower.indexOf(".mp4") >= 0) return "mp4";
  return "auto";
}

function kkSubLanguage(label) {
  var v = String(label || "").trim().toLowerCase();
  if (v === "en" || v === "eng" || v.indexOf("english") >= 0) return "English";
  if (v === "ms" || v === "msa" || v === "may" || v.indexOf("malay") >= 0 || v.indexOf("melayu") >= 0) return "Malay";
  if (v === "id" || v === "ind" || v.indexOf("indonesia") >= 0) return "Indonesian";
  return null;
}

function kkSubtitles(context) {
  return kkKey(KISSKH_SUBTITLE_KEY_API, context.episode.id, "subtitle-key").then(function(key) {
    var url = KISSKH_MAIN + "/api/Sub/" + encodeURIComponent(String(context.episode.id)) + "?kkey=" + encodeURIComponent(key);
    return kkFetch(url, { method: "GET", headers: kkHeaders() }, 9000, false);
  }).then(function(items) {
    if (!Array.isArray(items)) return [];
    var seen = {};
    return items.map(function(item) {
      var language = kkSubLanguage(item && item.label);
      var url = String(item && item.src || "").trim();
      if (!language || !url || /\.txt(?:$|\?)/i.test(url)) return null;
      if (url.indexOf("//") === 0) url = "https:" + url;
      else if (url.indexOf("/") === 0) url = KISSKH_MAIN + url;
      if (!/^https?:\/\//i.test(url)) return null;
      var key = language.toLowerCase() + "|" + url;
      if (seen[key]) return null;
      seen[key] = true;
      return { language: language, label: language, url: url };
    }).filter(Boolean);
  }).catch(function(error) {
    kkLog("subtitle", "skipped", error && error.message ? error.message : String(error));
    return [];
  });
}

function kkStreams(context) {
  var detail = context.detail;
  var episode = context.episode;
  return kkKey(KISSKH_VIDEO_KEY_API, episode.id, "video-key").then(function(key) {
    var slug = kkSlug(detail.title || "");
    var number = kkEpisodeNumber(episode.number);
    var referer = KISSKH_MAIN + "/Drama/" + slug + "/Episode-" + number + "?id=" + encodeURIComponent(String(detail.id || "")) + "&ep=" + encodeURIComponent(String(episode.id)) + "&page=0&pageSize=100";
    var api = KISSKH_MAIN + "/api/DramaList/Episode/" + encodeURIComponent(String(episode.id)) + ".png?err=false&ts=&time=&kkey=" + encodeURIComponent(key);
    return kkFetch(api, { method: "GET", headers: kkHeaders({ "Referer": referer }) }, 10000, false).then(function(source) {
      return { source: source || {}, referer: referer };
    });
  }).then(function(result) {
    var urls = [result.source.Video, result.source.video, result.source.ThirdParty, result.source.thirdParty]
      .map(function(value) { return String(value || "").trim(); })
      .filter(Boolean);
    var seen = {};
    var direct = urls.filter(function(url) {
      return /^https?:\/\//i.test(url) && (/\.m3u8(?:$|\?)/i.test(url) || /\.mp4(?:$|\?)/i.test(url) || /\.mpd(?:$|\?)/i.test(url));
    }).filter(function(url) {
      if (seen[url]) return false;
      seen[url] = true;
      return true;
    });
    if (!direct.length) throw kkError("video", "no direct HLS, MP4 or DASH source");
    return kkSubtitles(context).then(function(subtitles) {
      return direct.map(function(url) {
        var quality = kkQuality(url);
        return {
          name: "KissKH",
          title: "KissKH " + quality,
          url: url,
          quality: quality,
          provider: "kisskh",
          type: kkType(url),
          headers: {
            "User-Agent": KISSKH_UA,
            "Referer": KISSKH_MAIN + "/",
            "Origin": KISSKH_MAIN
          },
          subtitles: subtitles
        };
      });
    });
  });
}

function getStreams(tmdbId, mediaType, season, episode) {
  var started = kkNow();
  kkLog("provider", "start", "tmdbId=" + String(tmdbId) + " type=" + String(mediaType) + " season=" + String(season || "") + " episode=" + String(episode || ""), started);
  return kkResolveTmdb(tmdbId, mediaType)
    .then(kkSearch)
    .then(kkLoadDetails)
    .then(function(details) { return kkSelectEpisode(details, season, episode); })
    .then(kkStreams)
    .then(function(streams) {
      kkLog("provider", "ok", "streams=" + streams.length, started);
      return streams;
    })
    .catch(function(error) {
      kkLog("provider", "failed", error && error.message ? error.message : String(error), started);
      throw error;
    });
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { getStreams: getStreams };
} else {
  global.getStreams = getStreams;
}
